version: '3'
services:

  #PHP Service
  app_laravel-booking:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:latest
    container_name: app_laravel-booking
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app_laravel-booking
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver_laravel-booking:
    image: nginx:alpine
    container_name: webserver_laravel-booking
    restart: unless-stopped
    tty: true
    environment:
    - VIRTUAL_PORT=80
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db_laravel-booking:
    image: mysql:5.7.22
    container_name: db_laravel-booking
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-booking
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db_laravel-booking
    ports:
      - "8080:80"
    environment:
       - PMA_ARBITRARY=1
    networks:
       - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
